CREATE TABLE TASKLIST (
    TASKID INT PRIMARY KEY,
    TASKNAME NVARCHAR(100),
    TASKDESC NVARCHAR(255),
	STATUS VARCHAR(50),
    CREATEDATE DATETIME,
	DEADLINE DATETIME;
);

CREATE TABLE ACCOUNT (
    USERNAME VARCHAR(30) PRIMARY KEY,
	PASS CHAR(30),
	CONFIRM CHAR(30)
);