/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import database.Connect;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class TodoListMain extends javax.swing.JFrame {

    /**
     * Creates new form TodoListMain
     */
    public TodoListMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TaskList = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        titleInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        descInput = new javax.swing.JTextField();
        deadLine = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        createDate = new javax.swing.JTextField();
        addtask = new javax.swing.JButton();
        deleteTask = new javax.swing.JButton();
        updateTask = new javax.swing.JButton();
        showTasks = new javax.swing.JButton();
        showTask2 = new javax.swing.JButton();
        signout = new javax.swing.JButton();
        validatordecs = new javax.swing.JLabel();
        validatorId = new javax.swing.JLabel();
        validatorName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(99, 88, 220));
        jLabel5.setText("Tìm kiếm");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, -1));

        txtSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtSearch.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtSearch.setText("     ");
        txtSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 400, 44));

        TaskList.setBackground(new java.awt.Color(204, 204, 204));
        TaskList.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        TaskList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Tên Công Việc", "Mô Tả Công Việc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TaskList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1260, 190));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(99, 88, 220));
        jLabel9.setText("ID Công Việc");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, -1));

        idInput.setBackground(new java.awt.Color(204, 204, 204));
        idInput.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        idInput.setText("     ");
        idInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInputActionPerformed(evt);
            }
        });
        getContentPane().add(idInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 400, 44));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(99, 88, 220));
        jLabel2.setText("Tên Công Việc");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        titleInput.setBackground(new java.awt.Color(204, 204, 204));
        titleInput.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        titleInput.setText("     Complete Work Assignment");
        titleInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(titleInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 400, 44));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(99, 88, 220));
        jLabel3.setText("Mô tả công việc");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        descInput.setBackground(new java.awt.Color(204, 204, 204));
        descInput.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        descInput.setText("     Complete The I/O Notes Task");
        descInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        descInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descInputActionPerformed(evt);
            }
        });
        getContentPane().add(descInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 400, 40));

        deadLine.setBackground(new java.awt.Color(204, 204, 204));
        deadLine.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        deadLine.setText("     ");
        deadLine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deadLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deadLineActionPerformed(evt);
            }
        });
        getContentPane().add(deadLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, 210, 44));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(99, 88, 220));
        jLabel7.setText("Ngày Khởi Tạo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(99, 88, 220));
        jLabel8.setText("Ngày Hoàn Thành");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, -1, -1));

        createDate.setBackground(new java.awt.Color(204, 204, 204));
        createDate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        createDate.setText("     ");
        createDate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        createDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDateActionPerformed(evt);
            }
        });
        getContentPane().add(createDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 360, 210, 44));

        addtask.setBackground(new java.awt.Color(99, 88, 220));
        addtask.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addtask.setForeground(new java.awt.Color(255, 255, 255));
        addtask.setText("THÊM CÔNG VIỆC");
        addtask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtaskActionPerformed(evt);
            }
        });
        getContentPane().add(addtask, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 160, 49));

        deleteTask.setBackground(new java.awt.Color(99, 88, 220));
        deleteTask.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteTask.setForeground(new java.awt.Color(255, 255, 255));
        deleteTask.setText("XÓA CÔNG VIỆC");
        deleteTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTaskActionPerformed(evt);
            }
        });
        getContentPane().add(deleteTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 170, 49));

        updateTask.setBackground(new java.awt.Color(99, 88, 220));
        updateTask.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateTask.setForeground(new java.awt.Color(255, 255, 255));
        updateTask.setText("SỬA CÔNG VIỆC");
        updateTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTaskActionPerformed(evt);
            }
        });
        getContentPane().add(updateTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 170, 49));

        showTasks.setBackground(new java.awt.Color(99, 88, 220));
        showTasks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showTasks.setForeground(new java.awt.Color(255, 255, 255));
        showTasks.setText("Show Tasks");
        showTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTasksActionPerformed(evt);
            }
        });
        getContentPane().add(showTasks, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, 140, 50));

        showTask2.setBackground(new java.awt.Color(99, 88, 220));
        showTask2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showTask2.setForeground(new java.awt.Color(255, 255, 255));
        showTask2.setText("Refresh");
        showTask2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTask2ActionPerformed(evt);
            }
        });
        getContentPane().add(showTask2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 140, 50));

        signout.setBackground(new java.awt.Color(99, 88, 220));
        signout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signout.setForeground(new java.awt.Color(255, 255, 255));
        signout.setText("Sign Out");
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });
        getContentPane().add(signout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 530, 140, 50));
        getContentPane().add(validatordecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, -1));
        getContentPane().add(validatorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));
        getContentPane().add(validatorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public Connect conn = new Connect();
    private void showTask() {
    ResultSet rs = null;
    Statement st = null;
    Connection con = null;
    try {
        // Kết nối tới cơ sở dữ liệu
        con = conn.getConnection();
        st = con.createStatement();
        String query = "SELECT * FROM TASKLIST";
        rs = st.executeQuery(query);

        // Lấy thông tin cột từ ResultSetMetaData
        ResultSetMetaData rsmd = rs.getMetaData();
        DefaultTableModel model = (DefaultTableModel) TaskList.getModel();
        int cols = rsmd.getColumnCount(); // Số cột
        String[] colName = new String[cols];

        for (int i = 0; i < cols; i++) {
            colName[i] = rsmd.getColumnName(i + 1); // Lấy tên cột
        }
        model.setColumnIdentifiers(colName); // Đặt tiêu đề cột

        // Xóa các hàng cũ để tránh trùng lặp dữ liệu
        model.setRowCount(0);

        // Thêm dữ liệu vào bảng
        while (rs.next()) {
            Object[] row = new Object[cols];
            for (int i = 0; i < cols; i++) {
                row[i] = rs.getObject(i + 1); // Lấy giá trị từng cột
            }
            model.addRow(row);
        }

        // Đóng kết nối
        st.close();
        con.close();
        rs.close();

        // Cập nhật trạng thái các nút
        signout.setVisible(true);
        showTasks.setVisible(false);
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idInputActionPerformed

    private void descInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descInputActionPerformed

    private void deadLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deadLineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deadLineActionPerformed

    private void createDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createDateActionPerformed

    private void addtaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtaskActionPerformed
        // TODO add your handling code here:
        String title = titleInput.getText().trim();
        String desc = descInput.getText().trim();
        String id = idInput.getText().trim();
        if(title.isEmpty()){
            validatorName.setText("Vui lòng nhập tên công việc!");
            validatorName.setBackground(Color.RED);
        }
        else{
            validatorName.setText("");
        }
        if(desc.isEmpty()){
            validatordecs.setText("Vui lòng nhập mô tả công việc!");
        }
        else{
            validatordecs.setText("");
        }
        if(id.isEmpty()){
            validatorId.setText("Vui lòng nhập ID!");
        }

        int idTask;
        try{
            idTask = Integer.parseInt(id);
        }catch(NumberFormatException e){
            validatorId.setText("Vui lòng nhập ID phải là số nguyên!");
        }
        try{
            Connection con = conn.getConnection();
            String query = "INSERT INTO TASKLIST (TASKID,TASKNAME,TASKDESC) VALUES (?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(query);

            pst.setInt(1, Integer.parseInt(id)); // Convert id to integer
            pst.setString(2, title);
            pst.setString(3, desc);

            int rowsAffected = pst.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Task Added - Refresh to see updated Task List");
            } else {
                JOptionPane.showMessageDialog(null, "Task could not be added.");
            }
            pst.close();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_addtaskActionPerformed

    private void deleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTaskActionPerformed

    private void updateTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTaskActionPerformed

    private void showTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTasksActionPerformed
        // TODO add your handling code here:
        showTask();
    }//GEN-LAST:event_showTasksActionPerformed

    private void showTask2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTask2ActionPerformed
                                          
        // TODO add your handling code here:
        try{
        DefaultTableModel model = (DefaultTableModel) TaskList.getModel();
        model.setRowCount(0);
        txtSearch.setText("");
        titleInput.setText("");
        descInput.setText("");
        deadLine.setText("");
        validatorId.setText("");
        validatorName.setText("");
        validatordecs.setText("");

        showTask();
        }catch(ClassCastException e){
            JOptionPane.showMessageDialog(this, "Tasklist khong su dung default table model","Loi",JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Da xay ra loi khi tai du lieu!", "loi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_showTask2ActionPerformed

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        home n = new home();
        n.setVisible(true);
    }//GEN-LAST:event_signoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TodoListMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TodoListMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TodoListMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TodoListMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TodoListMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TaskList;
    private javax.swing.JButton addtask;
    private javax.swing.JTextField createDate;
    private javax.swing.JTextField deadLine;
    private javax.swing.JButton deleteTask;
    private javax.swing.JTextField descInput;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton showTask2;
    private javax.swing.JButton showTasks;
    private javax.swing.JButton signout;
    private javax.swing.JTextField titleInput;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JButton updateTask;
    private javax.swing.JLabel validatorId;
    private javax.swing.JLabel validatorName;
    private javax.swing.JLabel validatordecs;
    // End of variables declaration//GEN-END:variables
}
